### ISSUE TITLE
open in new window

### ISSUE THREAD

**Issue by applemate** [peterldowns/iterm2-finder-tools#1]
Hi, great stuff. Do you know how to make it open in new window instead new tab?

**Comment by peterldowns** [comment]
Should be a simple modification to the script to always create a new window – see the code here https://github.com/peterldowns/iterm2-finder-tools/blob/master/application/application.modern.applescript

**Comment by ghost** [comment]
Hey, I was looking for the same feature. If you change one line in the code (make new terminal), it works: 

```
on run {input, parameters}
  tell application "Finder"
    set dir_path to quoted form of (POSIX path of (folder of the front window as alias))
  end tell
  CD_to(dir_path)
end run

on CD_to(theDir)
  tell application "iTerm"
    try
      set newWindow to (make new terminal)
      tell newWindow
	create tab with default profile
	set sesh to current session
      end tell
    on error
      set newWindow to (create window with default profile)
      tell newWindow
        set sesh to current session
      end tell
    end try

    tell sesh
	write text "cd " & theDir & ";"
    end tell
  end tell
end CD_to
```

EDIT: Updated the code above by removing escaped HTML "$amp;" with "$".

**Comment by peterldowns** [comment]
Thanks @weisso -- @craigcosmo, hope that helps.

**Comment by jrochkind** [comment]
Copying and pasting @weisso 's example doesn't work, because somehow `&` have been escaped as `&amp;`. Replace `&amp;` in the line `write text "cd " &amp; theDir &amp; ";"` with plain old `&`, and it works.

**Comment by peterldowns** [comment]
Yeah, looks like @weisso copied that code out of one of [the workflow files](https://github.com/peterldowns/iterm2-finder-tools/blob/master/Open%20iTerm.app/Contents/document.wflow) that are built by the `build.py` script. To make changes to the code, edit the `.javascript` files in the `service` and `application` folders and then run `build.py`.

**Comment by ghost** [comment]
I am sorry about that! I fixed it in the response.
