### ISSUE TITLE
Focus iTerm

### ISSUE THREAD

**Issue by lumpysimon** [peterldowns/iterm2-finder-tools#2]
Is it possible to automatically move focus to the iTerm window after opening a folder, rather than focus staying on the Finder window?

**Comment by peterldowns** [comment]
Should be, some cursory googling pointed me to [this stackoverflow example](http://stackoverflow.com/questions/14773974/set-focus-to-specific-window-of-an-application-using-applescript). I'd be happy to accept a PR with this change if you can make it work.
