### ISSUE TITLE
Shortcut not working under Sierra 10.12.5 

### ISSUE THREAD

**Issue by besserwisser** [peterldowns/iterm2-finder-tools#4]
For me the Shortcut is not working under Sierra. I have tried multiple Key combinations, but none is working. It just happenings nothing, like I haven't pressed anything.

Have your experienced the same issue?

Thanks

**Comment by Bartcardi** [comment]
I have too, unfortunately. The rest is working perfectly.

**Comment by peterldowns** [comment]
The issue I've noticed is that the shortcut sometimes doesn't work unless iTerm2 is already running, and I mentioned it in the README:

> Unfortunately, it seems that this keyboard shortcut will only work if iTerm2 is already running.

but I'm not on Sierra so I'm not sure if this is the same issue. Sorry, I don't have a fix/workaround at this time :(

**Comment by curby** [comment]
Something like this might work.  I'm not on Sierra so I can't test.  I can try to revisit after I upgrade.  

```applescript
# Launch iTerm if it isn't running already, optionally remembering whether it was already open
if application "iTerm" is running then
	display dialog "iTerm already running" buttons {"Sure"} default button {"Sure"}
else
	tell application "iTerm" to activate
end if

# Tell iTerm to change directory, and activate (unless you know you activated above) to focus
```

EDIT: from https://stackoverflow.com/questions/16064957/how-to-check-in-applescript-if-an-app-is-running-without-launching-it-via-osa

By the way, any chance to re-open this issue?  Seems like (1) it's not fixed but hopefully (2) it could be.
