### ISSUE TITLE
An alternative

### ISSUE THREAD

**Issue by casouri** [peterldowns/iterm2-finder-tools#7]
I find 
``` applescript
on run {input, parameters}
	tell application "Finder"
		set dir_path to quoted form of (POSIX path of (folder of the front window as alias))
	end tell
	do shell script ({"open ", dir_path, " -a iterm"} as string)
end run
```
Works well. And it opens the directory in a new tab. 

I only tested this snippet as application, but service should work, too.

I'm not very familiar with applescript, if there is any problem please point out 😄

**Comment by peterldowns** [comment]
Hey @casouri, I like this a lot! Would you be willing to submit a PR? (Sorry for my incredibly long delay in responding to this 😭)

**Comment by casouri** [comment]
No worries! That's quite normal. I'm happy to submit a PR; the thing is though, I don't really remember how does this work anymore...

**Comment by peterldowns** [comment]
I'm going to close this issue for now, but I'd be happy to accept a PR with this change!
