### ISSUE TITLE
Unable to drag the icon to the toolbar

### ISSUE THREAD

**Issue by zakiaziz** [peterldowns/iterm2-finder-tools#8]
I see an issue was opened here: https://github.com/peterldowns/iterm2-finder-tools/issues/3 but no solution listed. I'm on OSX Mojave and wondering if you guys have any ideas as to what may be the issue here.

**Comment by cmosetick** [comment]
@zakiaziz 
I'm on MacOS 10.14.1 (Mohave) as well and I just held down the Command button on my keyboard (Apple button) while I dragged `Open iTerm.app` into the top of an open Finder window.

It's noted in the current version of the README.md file pretty well on lines 46 and 47:
`https://raw.githubusercontent.com/peterldowns/iterm2-finder-tools/49b1fe78bb50329b864902850104504ccfb53b45/README.md`

```
You can then add it to your Finder toolbar by dragging it in 
while holding the command and option keys 
(pre-Sierra) or while holding the command key (Sierra or later).
```

**Comment by zakiaziz** [comment]
@cmosetick Thanks for the response I tried it again and it worked. Maybe last time I wasn't holding down `cmd`? Anyways thanks for the help.
